### PR TITLE
Friendship Milestone2

### PR DESCRIPTION
**Pull request by karvel-code**
In this section I have:
- Created the friendship model.
- Added the various associations involved within the models.
- Created functions that are important in relating with the models and their associations.
- Added different sections which include 'unconfirmed requests' and 'friends' in the view.
- Added the various required rspec tests.

### CODE REVIEW

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Invalid :red_circle:           
### Hello @karvel-code  :wave: 

You should make sure that your repo looks professional before review. 
- Pull request description is empty, kindly make sure you provide a description of the feature you introduced in the branch as it makes you repo professional and easy to see an overview of the features introduced. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).   
- Your GitHub workflows are not configured correctly and GitHub actions are not running. Please take a step back and make sure your linters.yml file matches with [this](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml) and Github actions are running.

#### This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 
## Hello @karvel-code, good job so far with your project especially with your models :+1: 

### To improve:

- [x] You have some uncommitted code.
- [x] I should be able to send friend request only once. Currently, in your app, I can send a friend request to the same person multiple times. Screenshot from 2021-07-02 18-55-23
- [x] Even after I accept a friend request he still is not added as my friend hence I can again send him a friend request. Kindly fix this
- [x] There is a button to invite user to friendship on the users list page and on single-user page, currently in your app you don't have it in the single-user page. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Posts timeline includes posts written by logged-in user and their friends currently in your app the timeline includes posts from everybody not just their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### If you have any question with regards to  the requirements add a comment here and I will reply ASAP :thought_balloon: 

# HAPPY CODING :computer: :desktop_computer:

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The friendship request issue now works just fine.
    2. The app runs as expected. 👍🏽 

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] I'm currently unable to access the single-user page. This error is raised. Give it a quick fix.
Screenshot from 2021-07-07 12-44-07


#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User can invite friends :+1: 
- User can see friendships requests :100: 
- I have access to the single-user page :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] It will be perfect if` User A` is not able to send a friend request to `User B` if there is already a pending friend request from `User B to User A`.


Nice to have [OPTIONAL] :

- [ ] It will be nice if there is no logic in your view. Please use helpers.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by afanimartin — APPROVED** [review]
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested change. Merge and proceed to the next milestone.

### Martin Afani
#### Slack: whiz25

**Pull request merged**
